# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-01 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_sha1', models.CharField(max_length=40)),
                ('title', models.TextField()),
                ('url', models.CharField(max_length=2083)),
                ('image', models.CharField(max_length=2083)),
                ('type', models.CharField(max_length=40)),
                ('quality', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('category', models.TextField()),
                ('tags', models.TextField()),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=10)),
                ('actor', models.TextField()),
                ('imdb', models.CharField(max_length=40)),
                ('view', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('crawl_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'films',
            },
        ),
    ]
